### ISSUE TITLE
Allow typescript definition at @types/command-line-args of commandLineArgs to accept a readonly array

### ISSUE THREAD

**Issue by ellis** [75lb/command-line-args#104]
Could you please update the typescript definitions so that the `commandLineArgs` function can accept a Readonly array of options? The function definition could then look something like this:

```typescript
declare function commandLineArgs(
	optionDefinitions: ReadonlyArray<commandLineArgs.OptionDefinition>,
	options?: commandLineArgs.ParseOptions
): commandLineArgs.CommandLineOptions;
```

**Comment by 75lb** [comment]
could you post a PR on [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/command-line-args) please? I don't use Typescript, I learned the basics a year or two ago but have forgotten everything already. If you post a PR, I will check and approve it if all is good.
