### ISSUE TITLE
Aliases should be nullable

### ISSUE THREAD

**Issue by Androz2091** [75lb/command-line-args#107]
When I don't add the `alias` property to an Argument object:
```js
const optionDefinitions = [
    { name: "checkfor", type: String, multiple: true }
];
```
like this, it throws the following error:
`INVALID_DEFINITIONS: Invalid option definition: an alias must be a single character`
It shouldn't, no? We shouldn't have to specify an alias

**Comment by 75lb** [comment]
An alias is optional - something else is causing this issue, please double-check all definitions.. if you want some help, post a full code sample which I can run..

**Comment by 75lb** [comment]
Closing as stale.
