### ISSUE TITLE
recommended way to handle help?

### ISSUE THREAD

**Issue by trusktr** [75lb/command-line-args#109]
Judging from the examples, it looks like users of command-line-args need to decide when/how to show a help screen (f.e. with command-line-usage). 

Is there some way to make this easier? F.e. `stopAtFirstUnknown` means if there's actually a valid option after the unknown, it will be skipped (right?). So in this case, we don't just want to skip ahead, we want to show the help screen.

How do you manage this in your apps? Any recommendation?

**Comment by 75lb** [comment]
It's just a matter of taste - it's up to you to handle exceptions or inspect `_unknown` and decide whether to display help or not. I can't think of a definitive answer.
