### ISSUE TITLE
How to set a boolean value that defaults to true to false.

### ISSUE THREAD

**Issue by LiamKarlMitchell** [75lb/command-line-args#113]
```
{ name: 'dryrun', type: Boolean, defaultValue: true, description: 'Prevents writing changes' },
```

I tried
--dryrun=false
--dryrun=0
--dryrun=n
--dryrun false

Ended up just using Number type argument.

https://github.com/75lb/command-line-args/blob/master/lib/argv-parser.mjs#L45
Could this be modified to check if there is an attached value and if so if its truthy set to true falsey set to false?

**Comment by 75lb** [comment]
Already answered [here](https://github.com/75lb/command-line-args/issues/108)
