### ISSUE TITLE
Multiple as a single type?

### ISSUE THREAD

**Issue by OmgImAlexis** [75lb/command-line-args#114]
Is it possible to have multiple values returned as a single custom type?

For example the wiki shows this.
```
$ node example/type.js package.json nothing.js
{ file:
   [ FileDetails { filename: 'package.json', exists: true },
     FileDetails { filename: 'nothing.js', exists: false } ] }
```

Whereas I'm wanting this.
```
$ node example/type.js package.json nothing.js
{ file:
   [ FileDetails { filenames: ['package.json', 'nothing.js'], exists: true } ] }
```

**Comment by 75lb** [comment]
Hi, no the `type` function specifies a type for each individual value, by design.. 

In your case, if you start with this..

```js
const options = commandLineArgs(..)
```

.. and `options.files` contains an array of `FileDetails` instances then you could pass them into a `FileLIst` class.. 

```js
class FileList {
  constructor (files) {
    this.files = files
    this.exists = files.every(f => f.exists)
  }
}

const fileList = new FileList(options.file)
```

**Comment by OmgImAlexis** [comment]
Unfortunately in my case that won’t work as it’s not files; I was just using that as an example.

I’ll have to just use strings and combine then after the fact.
