### ISSUE TITLE
Support concatenated .multiple for string arguments

### ISSUE THREAD

**Issue by andrisi** [75lb/command-line-args#124]
If I'd like the following to work, I have to manually join the name array I get. For strings, you could add an option top concatenate params, so I get the full string, without quoting it. For now I get ['luke', 'skywalker'] which is ok in some cases, but not always. So something like a .join option with a char that is used to join() the array elements. Thanks.

`node test.js --name luke skywalker --age 40`

**Comment by 75lb** [comment]
> I have to manually join the name array I get

Yes, i'm afraid you do.. you're asking me to permanently embed a specific preference relating to a specific usage scenario into the library.. if i did that for every user's preference the library would be changing every week and stability would be compromised.. sorry.

**Comment by andrisi** [comment]
To me it seemed like a generic enough use case and option, and quite simple one. Your library is an excellent manifestation of doing something for whoever needs that generic functionality.  What other requests like this you get, I'm courious. In any case, thanks for your excellent library.
