### ISSUE TITLE
docs for Usage guide generation  is missing

### ISSUE THREAD

**Issue by geetee24** [75lb/command-line-args#126]
need docs to explain how to pass commandLineArgs object to command-line-usage.

it is not obvious.

Thank you

**Comment by 75lb** [comment]
the links to the comand-line-usage docs [are in the command-line-args readme](https://github.com/75lb/command-line-args#usage-guide-generation), can you be more specific what is not obvious please? Thanks

**Comment by Newman1515** [comment]
# Code of Conduct

Hi, thanks for getting involved! The conduct rules are straight forward.. 

* We consider your ethnicity, age, gender, sexuality and religion irrelevent.
* All feedback welcome. Constructive criticism is both valid and useful. However, keep it respectful please.
* This is a joint effort! We learn, improve and benefit together.

**Comment by 75lb** [comment]
Closing this for now as the Usage guide docs are not missing, the links are present and no-one has raised this as an issue before.. If you have any specific suggestions to improve the docs - please submit a PR.
