### ISSUE TITLE
Support required options

### ISSUE THREAD

**Issue by marke-apexit** [75lb/command-line-args#129]
Provide a way to specify that an option is required so that parsing of the options can automatically detect missing options and ideally automatically display the 'help' message and exit.

**Comment by karfau** [comment]
https://github.com/75lb/command-line-args/wiki/Validation#why-is-validation-not-built-into-the-module

> Because this module specialises in one task - finding and extracting values set against defined options in `process.argv`. Whether those extracted values meet certain criteria or not is for the consuming application, or separate module to decide. Early versions of the module included simple validation features but they attracted too much conflicting opinion and general issue noise, resulting in reduced module stability. The module author decided the concern of testing whether parsed values meet certain criteria was a separate one and preferred not to maintain it as part of this project.
