### ISSUE TITLE
Parsing arguments in Node script

### ISSUE THREAD

**Issue by ktyacke** [75lb/command-line-args#13]
First off, thanks for putting together such an awesome module! This is exactly the tool I need, just one minor thing I can't seem to figure out: How do I parse the command line arguments in a script?

For example
In my package.json I have the following

```javascript
"scripts": {
    "start": "node ./bin/www"
  }
```

and in the www script I call

```javascript
var commandLineArgs = require('command-line-args');

var cli = commandLineArgs([ 
  { name: "port", alias: "p", type: String, defaultValue: 4000 }
]);

var options = cli.parse();
console.log("Options: ", options);
console.log("Argv: ", process.argv);
```

If I then call `npm start --port 2828` the default value of 4000 gets set; however, no matter what I do, the options object never parses the value passed in from the command line. If I inspect the process.argv Array, I can see that the value I passed in (2828) is in fact listed, but it doesn't seem to get picked up by cli.parse(). I also tried manually passing the process.argv array into the cli.parse method, but that had no impact.

Do you have any pointers on what I might need to do to get this up and running?

Thanks in advance!

**Comment by 75lb** [comment]
thank you, i'm pleased you like it :) the alternatives didn't suit me, so.. 

take a look `npm help run-script`.. the syntax is
```
$ npm run-script <command> [-- <args>...]
```

so, try this
```
$ npm run start -- --port 2828
```

**Comment by ktyacke** [comment]
Thank you so much for the uber fast response! I actually was just reading an article on the `--` command. It seems an awfully strange way to pass arguments on to your scripts (I would assume it would just do this by default). Perhaps this could be something worth visiting in a future feature update (or maybe an idea for a new module for me to write) =]

Thanks again!

**Comment by 75lb** [comment]
you're welcome :+1:
