### ISSUE TITLE
New feature: option to retain inputs

### ISSUE THREAD

**Issue by zanerock** [75lb/command-line-args#135]
Because inputs are transformed, the original user input can get lost. It can be useful to retain the user input for multiple reasons. 

One example in particular, a companion validation library might, at the very least, wish to reflect the invalid value back to the user. E.g., "Option '--foo' value 'a' is not a valid number." With more sophisticated processing, there might be different error reports based on the original input. E.g., if we had option def `{ name: 'num', type: (val) => parseInt(val) }` then both `--num ''` and `--num ab` would fail, but we might respond "Option 'num' is required." in the first instance and "Option 'num' value 'ab' is must be an integer." Even worse, `--num 1.2` would result in a value of 1. In this case, it's necessary to inspect the original input to know that it's invalid input.

So, we add `retainInput` to `commandLineArgs`. When true, an `_inputs` field is included in the result. The result is a mapping between the option name and the input or inputs (where `multiple: true`). `_inputs` respets `camelCase`.

**Comment by 75lb** [comment]
Code you do me a favour please and paste some reproduction code I can run to quickly demonstrate the issue. Cheers!

**Comment by zanerock** [comment]
Well, I'm now thinking you can achieve the same effect by supplying custom `type` functions like:
```javascript
const Integer = (val) => {
  if (input.match(/^-?(?:0|[1-9]\d*)$/) === null) {
    throw new Error(`Option 'integer' value '${input}' is a number, but must also be an integer.`)
  }
  const value = parseInt(input)
  if (value === NaN) {
    throw new Error(`Option 'integer' value '${input}' does not parse as a number.`)
  }
  return value  
}
```
So I'll go ahead and close the issue.

Just to complete the thought, I was thinking of something like this:
```javascript
import commandLineArgs from 'command-line-args'

const spec = [
  { name: 'integer', type: Number }
]
const options = commandLineArgs(spec, { retainInput: true })
const value = options.integer
const input = options._input.integer

if (value === NaN) {
  throw new Error(`Option 'integer' value '${input}' does not parse as a number.`)
}
if (input.test(/-?(?:0|[1-9]\\d*)/) !== true) {
  throw new Error(`Option 'integer' value '${input}' is a number, but must also be an integer.`)
}
```
