### ISSUE TITLE
Error when used with cluster

### ISSUE THREAD

**Issue by wenjunche** [75lb/command-line-args#14]
First, think you for this great tool.

I am having an issue with using it with node cluster module.  Here is a simple script to reproduce it:

```javascript
var cluster = require("cluster");
var commandLineArgs = require('command-line-args');
var cli = commandLineArgs([{ name: 'config', type: String }]);

//var options = cli.parse(process.argv); // works fine
var options = cli.parse(); // "Cannot find module undefine" error

if (cluster.isMaster) {
    cluster.fork();  // fork one worker
} else {
    console.log('worker');
}
```

If I run cli.parse(process.argv), it works fine.  With cli.parse(), I am getting following error from worker process:

```javascript
Cannot find module '/Users/xxx/Documents/debug/undefined'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

I am running node 0.12.5 on Darwin Kernel Version 13.4.0

Thanks in advance!

**Comment by 75lb** [comment]
fixed and released in v2.1.1 - thanks for the report!

i'm pleased you like the library.. let me know if i can improve it at all :+1:
