### ISSUE TITLE
Halfway point for mutiple: true ?

### ISSUE THREAD

**Issue by eberls** [75lb/command-line-args#17]
I've got code where I want to specify multiple of an option, but I don't want the parser to be "greedy".
eg:
```
var CLA  = require('command-line-args');
var cli = CLA([
    { name: 'mech', alias: 'm', type: String,  multiple: true },
    { name: 'source',    alias: 's', type: FileDetails,  defaultOption: true },
]);
console.error(cli.parse());
```
`node lib/main.js -m one -m two somefile.taco`
would yield an `options` of
```
{  mech: [ "one", "two" ],
    src: { filename: "somefile.taco", exists: true } }
```
instead of
```
{ mech: [ "one", "two", "somefile.taco" ] }
```
  
  
  
Ideally such a mechanism would allow an accumulator for options that don't have arguments.
Such as allowing me to set the debug value to 3 by specifying -d multiple times.
eg:
`node lib/main.js -d -d -d -m one -m two somefile.taco`
having potentially the output of:
```
{ debug: 3, 
  mech: [ "one", "two" ],
  src: { filename: "somefile.taco", exists: true } }
```
(My experiments in writing a function ala FileDetails didn't go too well.)

This might also require an additional flag that indicates an arg doesn't take any value and is only a key.

**Comment by 75lb** [comment]
hi! yeah, this has cropped up before..  currently, `multiple` args "feed" on all values up until the next option, so to get the correct result you would need to write 
```
node lib/main.js -m one -m two -s somefile.taco
```

...which obviously means you can't specify `defaultOption` values immediately after `multiple` option values, as the library has no idea where the `multiple` values end and the `defaultOption` values begin.. 

so to solve it we need to "teach" the library where the `multiple` values end, but it would need to be an exact number - a range is too vague.. we'll need more config, something like:

```
{ name: 'mech', alias: 'm', type: String,  multiple: true, valueCount: 2 }
```

what do you think?

**Comment by eberls** [comment]
How about "maxValueCount"?
Theory would be that it would suck up at most that number of arguments? Though, I can't think of normal use cases where it would be more than 0 or 1.
I haven't done a code inspection yet, but it would seem like the '0' case would allow an array of booleans to be returned by setting
```
{ name: 'debug', alias: 'd', type: Boolean, multiple: true, maxValueCount: 0 }
```
It would be up to the consumer to attempt to aggregate.

An alternate would be to push null into the array so that
```
{ name: 'debug', alias: 'd', type: Number, multiple: true, maxValueCount: 1 }
```
would allow either `-d -d -d` or `-d 3` or  `-d 2 -d` to return
`[ '', '', '' ]`, `[3]`, or `[2, '']` respectively.  (Again, up to the consumer to reduce.)

**Comment by 75lb** [comment]
> Though, I can't think of normal use cases where it would be more than 0 or 1.

you can't think of a case where more than 1 value would be passed into a `multiple`? you also said `maxValueCount: 1` would allow `-d -d -d` (three values)..  I think i have failed to understand your `maxValueCount` semantics.. 

one thing to remember is that the `valueCount` must be an exact number, not a range (with a min or max).. the parser would need a definite indicator of when to stop parsing `multiple` values and when to begin parsing `defaultOption` values.. with this in mind, it might not be possible to satisfy your particular requirements.

all command-line parsers require some sort of delimiter to indicate the end of an array of values (typically `--`).. if you have a use case where you need to be specific where the defaultOptions begin then be specific: 

```
node lib/main.js -m one -m two -s somefile.taco
```
