### ISSUE TITLE
"description" missing in documentation

### ISSUE THREAD

**Issue by timo-klarshift** [75lb/command-line-args#18]
If you want to render cli.getUsage you can pass a `description` property to the options per item. This is not reflected in the documentation, but the usage example shows usage rendered with description. 

just to let you know ... i really like that project, thanks for that :+1:

**Comment by 75lb** [comment]
if you [look at](https://github.com/75lb/command-line-args#cligetusageoptions--string) the `.getUsage()` docs, there is [a link to the detailed docs](https://github.com/75lb/command-line-usage#getusagedefinitions-options--string-) where `description` is documented. Maybe i should make this more clear. 

let me know if there are any other issues!
