### ISSUE TITLE
cannot generate simple usage string after recent refactoring

### ISSUE THREAD

**Issue by kanosek** [75lb/command-line-args#19]
After you've refactored out command-line-usage there's no way I can generate simple usage string out of  list of `[ { name: 'first' }, { name: 'second' } ]` etc. option definitions. This breaks existing apps. One needs to carefully go through the docs.

My old code:
```
    opts = cliArgs([
    {
      name: 'dry_run',
      alias: 'n',
      type: Boolean
    },
    {
      name: 'help',
      alias: 'h',
      type: Boolean
    }]);
    console.log(opts.getUsage());
```

Needs to get extra wrapping to:
```
    defs = [
    {
      name: 'dry_run',
      alias: 'n',
      type: Boolean
    },
    {
      name: 'help',
      alias: 'h',
      type: Boolean
    }]
    opts = cliArgs(defs);
    console.log(getUsage({
      header: 'Options',
      optionList: opts_definitions
    }));
```

This could be clearer stated in docs when you mention command-line-usage.

**Comment by 75lb** [comment]
Hi, if you want to use the previous API for command-line-usage then install version 2, not 3. 

`npm install command-line-usage@2`

Using this module version you will not need to change any existing `getUsage` code.

**Comment by kanosek** [comment]
Yeah, thanks. Sorry I haven't checked v3.0.0 release notes that clearly state the breaking changes.

Still I suggest to elaborate a tiny bit the following line in README.md:

> A usage guide can be generated using command-line-usage.

by suggesting to wrap definitions into _optionList_ field of that's module argument; OR, to explicitely mention command-line-args in command-line-usage documentation.
