### ISSUE TITLE
Boolean options with defaultOptions

### ISSUE THREAD

**Issue by N4m** [75lb/command-line-args#20]
With these definitions...
`var optionDefinitions = [
    { name: 'help', alias: 'h', type: Boolean },
    { name: 'long', alias: 'l', type: Boolean },
    { name: 'paths', alias: 'p', type: String, defaultOption: true }
];`

and using the argv array...
`var argv = ['-l', '/etc'];`

Instead of getting `{ long: true, paths: 'etc' }` the result is `{ long: 'etc' }`

**Comment by 75lb** [comment]
Really? That sounds strange. Could you post or link to the full code to reproduce?

**Comment by N4m** [comment]
Sorry, to clarify, the above result is when I do not use the Boolean type. See bellow for more details/examples...

The code runs inside of vm2 currently so you wouldn't be able to run it as is, but here is the code...

`/*jshint esversion:6 */
var fs = require('fs');
var args = require('args');
var usage = require('usage');
var _ = require('lodash');
var colors = require('colors');
var columnify = require('columnify');
var optionDefinitions = [
    { name: 'help', alias: 'h', type: Boolean },
    { name: 'long', alias: 'l', type: Boolean },
    { name: 'paths', alias: 'p', type: String, defaultOption: true }
];

var argv = _.drop(argv);
var opts = args(optionDefinitions, argv);
console.log(opts);
if (opts.help || opts.help === null) {
    console.log(usage([{
        header: 'Usage',
        content: [
          '$ ls \[options\] [underline]{paths}...',
          '$ ls [bold]{--help}'
        ]
    }, {
        header: 'Options',
        optionList: this.inputOptions
    }]));
} else {
    var ls = [];
    if (argv.length === 0) {
        ls = fs.ls();
    } else {
        ls = fs.ls({path: opts.paths});
    }
    if (ls.length !== 0) {
        var contents = [];
        if (opts.long===null || opts.long === true) {
            _.forEach(ls, function(entry) {
                var newEntry = {
                    permissions: entry.permissions,
                    size: entry.size,
                    type: entry.type
                };
                if (entry.type == "dir") {
                    newEntry.name = colors.blue(entry.name);
                } else if (entry.type == "link") {
                    newEntry.name = colors.cyan(entry.name);
                } else {
                    newEntry.name = entry.name;
                }
                contents.push(newEntry);
                // console.log(entry);
            });
            console.log(columnify(contents));
        } else {
            _.forEach(ls, function(entry) {
                if (entry.type == "dir") {
                    contents.push(colors.blue(entry.name));
                } else if (entry.type == "link") {
                    contents.push(colors.cyan(entry.name));
                } else {
                    contents.push(entry.name);
                }
                // console.log(entry);
            });
            console.log(_.join(contents, ' '));
        }
    }
}`

You can see at the top I am using `console.log(opts);` to output the detected results. Here are some of the examples and results...

Using type: Boolean
`# ls -l /etc                                                                                                                       
{ long: true }`
Using type: Boolean
`# ls /etc -l                                                                                                                       
{ paths: '/etc', long: null }`

Using no type
`# ls -l /etc                                                                                                                       
{ long: '/etc' }`
Using no type
`# ls /etc -l                                                                                                                       
{ paths: '/etc', long: true }`

I am using this to replicate standard linux command behavior. This example is implementing the ls command inside of the vm2 context.

**Comment by N4m** [comment]
args and usage are actually command-line-args and command-line-usage

**Comment by 75lb** [comment]
Hi, i ran this script in node

```
var optionDefinitions = [
  { name: 'help', alias: 'h', type: Boolean },
  { name: 'long', alias: 'l', type: Boolean },
  { name: 'paths', alias: 'p', type: String, defaultOption: true }
];

var argv = ['-l', '/etc']

var commandLineArgs = require('command-line-args')
var options = commandLineArgs(optionDefinitions, argv)

console.log(options)
```

and the output is correct: 
```
{ long: true, paths: '/etc' }
```

Closing, as the library is behaving as expected.

**Comment by N4m** [comment]
Interesting. I ran that exact same code and got this...

`{ long: true }`

There must be some kind of a compatibility issue with https://github.com/patriksimek/vm2
I believe vm2 changes the context of a Boolean which is run in a proxy. Perhaps the Boolean object is not being set up correctly is due to it running in a vm2 is not working as expected.
Do you have any areas of the code you recommend me looking at to debug this issue while I test it in vm2 to narrow down the issue?

**Comment by 75lb** [comment]
i don't have any areas of the code to recommend as i don't have a clue about is happening with this vm2 issue.. The command-line-args codebase is pretty small, i'd appreciate if you try and isolate the issue and get back to me. I suppose you would need to compare execution of `commandLineArgs()` in both node and vm2 and see what differs. If there is a fix for this issue from my side i will look into it.

**Comment by N4m** [comment]
I made these changes and ran a rest both in regular node and vm2..

`
...
  /* walk argv building the output */
  argv.list.forEach(item => {
    if (option.isOption(item)) {
      def = definitions.get(item)
      if (!t.isDefined(output[def.name])) outputSet(output, def.name, def.getInitialValue())
      console.log(item);
      console.log(def);
      console.log(def.isBoolean());
      if (def.isBoolean()) {
        outputSet(output, def.name, true)
        def = null
      }
...
`

In vm2
`
OptionDefinition {                                                                                                                                                 
  name: 'long',                                                                                                                                                    
  type: [Function: Boolean],                                                                                                                                       
  alias: 'l',                                                                                                                                                      
  multiple: undefined,                                                                                                                                             
  defaultOption: undefined,                                                                                                                                        
  defaultValue: undefined,                                                                                                                                         
  group: undefined }                                                                                                                                               
false
`

In node

`
OptionDefinition {
  name: 'long',
  type: [Function: Boolean],
  alias: 'l',
  multiple: undefined,
  defaultOption: undefined,
  defaultValue: undefined,
  group: undefined }
true
`

**Comment by N4m** [comment]
Hmm... it's not pasting well

**Comment by 75lb** [comment]
you are using the wrong github-flavoured-markdown syntax for code blocks.. it's triple-backtick. 
https://guides.github.com/features/mastering-markdown/

**Comment by N4m** [comment]
yup, just fixed that

**Comment by 75lb** [comment]
try changing [this line](https://github.com/75lb/command-line-args/blob/master/lib/definition.js#L239) to 
```
return this.type.name === 'Boolean'
```

**Comment by N4m** [comment]
Ah, it is this...

```
isBoolean () {
    return this.type === Boolean
}
```

Yea... because the context is different and the command-line-args lib is at the top context while it's trying to compare it against a Boolean value which is just inside of a context, so they are not exactly the same

**Comment by N4m** [comment]
Did some research and this appears to work in both node, vm2... it tried a ES6 method first, if that fails it falls back to an ES5 method..

```
isBoolean () {
    // First try ES6 Method
    if (this.type && this.type.name == "Boolean") {
        return true;
    } else { // Fall back to ES5 Method
        var result = /^function\s+([\w\$]+)\s*\(/.exec( this.type.toString() );
        if (result && result.length>=2 && result[1] == "Boolean") {
            return true;
        }
    }
    return false;
  }
```

Got help from this page http://stackoverflow.com/questions/2648293/javascript-get-function-name

With the change to isBoolean I get this in both node and node+vm2 ```{ long: true, paths: '/etc' }```

**Comment by 75lb** [comment]
good work, well done. Could you submit a PR please and i'll review it tonight after work 👍

**Comment by N4m** [comment]
Hmm... ran into a bug, just fixing it now and I will give you the fixed code
