### ISSUE TITLE
Allow for mandatory arguments

### ISSUE THREAD

**Issue by alsterg** [75lb/command-line-args#26]

**Comment by duxing** [comment]
hi @75lb 
thx for sharing this amazing lib with us.
can you briefly share with us why you choose not to support this feature?

**Comment by 75lb** [comment]
Hi, it's a common question so I wrote an answer at the bottom of the [validation page](https://github.com/75lb/command-line-args/wiki/Validation).

**Comment by duxing** [comment]
fair point. thanks!
