### ISSUE TITLE
Equals (=) in argument throws "Invalid option"

### ISSUE THREAD

**Issue by swemaniac** [75lb/command-line-args#30]
Hi,

Thanks for this great lib!

However I can't use argument values such as `--url="my-url?q=123"` since the regex for parsing x=y arguments doesn't seem to be checking for quotes, which means my equal sign in the value will break it.

I believe this is a similar issue: #10

**Comment by 75lb** [comment]
fixed but i don't have enough time right now to test it as much as i'd like (i'm at work), so i pushed a pre-release for you in the meantime.. it's on the `next` tag: 

```
$ npm install command-line-args@next
```

let me know if it fixes your issue.

**Comment by swemaniac** [comment]
I've tried to break it but I can't - fix'd :) thanks!

**Comment by 75lb** [comment]
great, thanks for letting me know - will add some more test cases later then release.

**Comment by 75lb** [comment]
released in v3.0.3
