### ISSUE TITLE
Not sure how to send a value which starts with "--"

### ISSUE THREAD

**Issue by usergenic** [75lb/command-line-args#31]
I am writing a tool which has an option to pass flags for one of the CLI tools it invokes.  I assumed an invocation like this would work:
```
tattoo --wct-flags="--local firefox"
```
Unfortunately, command-line-args thinks I'm passing in 2 args. --wct-flags and --local which makes it sad at me.

Is there a way right now, that I'm not seeing, to pass a value that has a `-` prefix without command-line-args interpreting it as an option to parse?

**Comment by 75lb** [comment]
no, there's not a way right now but there should be - the way you described above should work fine.. i.e. this should work as you explicitly supplied the `=`:

```
tattoo --wct-flags="--local firefox"
```

however, this would continue be parsed as two separate options (as there is no way of determining whether you intended `--local` to be an option or value):

```
tattoo --wct-flags "--local firefox"
```

will get back to you

**Comment by usergenic** [comment]
Fwiw, I've temporarily worked around this by preprocessing argv before
calling the commandLineArgs function, to prefix values with a space in the
assignment-using-equals form and then trimming them after I get the options
object back from commandLineArgs.  Not ideal but I can get by for now.

**Comment by 75lb** [comment]
released in v3.0.4, documented [here](https://github.com/75lb/command-line-args#ambiguous-values)

**Comment by usergenic** [comment]
Thank you!  It will be nice to be able to remove my hack and upgrade to yours.  👍

**Comment by 75lb** [comment]
no probs, let me know if you find anything else.
