### ISSUE TITLE
using command-line-usage to print command-line-args definitions

### ISSUE THREAD

**Issue by bryanrasmussen** [75lb/command-line-args#32]
In your readme you say that command-line-usage can be used to generate a guide to using the tools. But it does not have an example of how to do that. 

I naively tried to do the following

```
const commandLineArgs = require('command-line-args');
const getUsage = require('command-line-usage')

const optionDefinitions = [
  { name: 'site', type: String, defaultValue: 'local', description: 'The site we want to test, by default it will be testing on your local host. Values are business, help, or local.'},
  { name: 'testTarget', type: String, defaultValue: 'pages', description: 'Values are either business or integration. In localhost it is assumed that pages are production, and components are integration' },
  { name: 'debug',  type: Number, defaultValue: 2, description: 'Passes value to phantomflow to control debugging - A value of 1 will output more logging, 2 will generate full page screenshots per test which can be found in the test-results folder. Forces tests onto one thread for readability. ' },
  { name: 'createReport', type: Boolean, defaultValue: false, description: 'Passes value to phantomflow as to whether there should be any report created' },
  { name: 'remoteDebug', type: Boolean, defaultValue: true, description: 'Enable PhantomJS remote debugging' },
  { name: 'help', alias: 'h', type: Boolean, defaultValue: false, description: 'Show this help message' },
  { name: 'dashboard', type: Boolean, defaultValue: false, description: 'Allow dashboard creation and display in command line' }
  
  
]
const options = commandLineArgs(optionDefinitions);
const usage = getUsage(optionDefinitions);
console.log(usage);
```

expecting that I would get some sort of legible report out, but I just get about 5 empty lines in my console. This is on Windows 10, latest version. 

I realize that the examples in the command-line-usage tool are quite different than yours, but I expected that if the guide says that command-line-usage can be used that there was someway of handling the command-line-args structure gracefully?

**Comment by 75lb** [comment]
did you read the [command-line-usage documentation](https://github.com/75lb/command-line-usage)?

**Comment by bryanrasmussen** [comment]
Yes, and I guess I must have misunderstood the command-line-args readme - where it says 

A usage guide can be generated using command-line-usage, for example:
....
right in the middle of talking about command-line-args capabilities I took that to mean that if you write a command-line-args compliant object and then pass it to command-line-usage it will understand that object and print it out although looking at the documentation for command-line-usage that didn't seem to be reasonable as the two object structures are quite different. 

Is it then that the meaning of the sentence 'A usage guide can be generated using command-line-usage...:' is not
   (using the optionsDefinition) A usage guide can be generated using command-line-usage... 
but rather 
   (if you need to generate a usage guide then) A usage guide can be generated using command-line-usage.... 
which is fine, I was just confused by the sentence and thought the two libraries were complementary.
