### ISSUE TITLE
Consider dropping core-js dependency

### ISSUE THREAD

**Issue by justinfagnani** [75lb/command-line-args#33]
core-js makes up the vast majority of the total install size of this package, it'd be really nice to remove it for projects that aren't already pulling it in. In some projects I maintain I've been asked to use another arg parser because of this.

The currently active LTS versions, 4 and 6, support all the ES6 features used here. Node 0.12 is still in maintenance, but only for two more weeks.

I'd be willing to submit a PR for this.

**Comment by 75lb** [comment]
hi @justinfagnani .. yes, it can go as only `Array.prototype.find` requires polyfilling within the module which doesn't warrant including all of core-js.. I've already done the work, will release later.. However, command-line-usage depends on table-layout which also pulls in core-js - that will remain for now (v0.12 users are still active).. will get back to you.

**Comment by 75lb** [comment]
released in v3.0.5.. i recently dropped 0.10 support and will kill off 0.12 across the board soon too, cheers.. let me know if there's anything else.

**Comment by justinfagnani** [comment]
Awesome, thanks for the quick turnaround!

0.12 goes of out maintenance in 7 days, so hopefully you can trim some more soon :)
