### ISSUE TITLE
Incorrect UNKNOWN_OPTION getting thrown

### ISSUE THREAD

**Issue by blakewest** [75lb/command-line-args#36]
Hi, I have a project where various files use your `commandLineArgs` lib. Generally speaking, it's great, and has proved super useful. However, I've run into a problem that is quite frustrating. 
Here's the issue: `scriptA` has X command line args, and `scriptB` has Y command line args. But `scriptA` requires `scriptB`. Now we have a problem. When I do the following...
```
// flag1 is defined in scriptA, but not in scriptB
node scriptA  --flag1
->  `UNKNOWN_OPTION`
```
I get... `UNKNOWN_OPTION`. Which is pretty messed up. The args I'm passing to `scriptA` are assuredly defined and valid. But I'm getting an error because `commandLineArgs` thinks I'm passing `flag1` to `scriptB`, which I'm not doing.

The order in which these are defined is irrelevant. My assumption now is that commandLineArgs checks for unknown params at definition time, though I don't know for sure.

It seems like commandLineArgs should be smart enough to separate this somehow. Maybe it tracks which file is defining which set of args and it could then, at run time, determine if the option is actually unknown *for the file that's getting called*. Or maybe it just concats all options getting defined within some global store, and it only cares about duplicate names within one  "definition call". 
My options for solving this are pretty lame. I either keep a global list of all options for all files, and require that, or maybe do a try catch (though unsure if that actually would work). But as a different issue alludes to, I can't just turn off the "Unknown option" error. 

Thoughts? Thanks! Otherwise this lib is great.

**Comment by 75lb** [comment]
Hi! To help me reproduce and fix this quickly, please supply some source - either real source or a simple test case.. paste it here or in a gist.. cheers!

**Comment by 75lb** [comment]
closing until we have reproduction steps.

**Comment by blakewest** [comment]
@75lb hey there, sorry for delay. I just put together an example repo reproducing the bug: https://github.com/blakewest/commandlineargsdemo

**Comment by 75lb** [comment]
thanks for the test case - very useful! I was able to track the issue within a few minutes. 

What you are seeing is the expected behaviour. You are parsing the command line twice - once in script A, once in script B. So, when you run this command: 

```
$ node scriptA.js --withHelper
```

it is accepted by script A (where it has a definition) but not script B (where it does not have a definition). 

Correct behaviour.

**Comment by blakewest** [comment]
@75lb thanks for checking it out, and it sounds like you get the situation. The behavior seems, if nothing else, unexpected. If it is expected, the error message could be clearer. It took me a while to realize what was even happening. As I run that line, I'm thinking, "I'm running scriptA with a valid argument to script A. Why does it think the argument is unknown?". And I would not expect that the command line args would get *validated* against files that are merely getting required, and not run.

But aside from that, just consider the use case that the repo replicates, which is... "Sometimes I run script A, and sometimes I run script B. Both have their own command line args, but they also share code amongst one another." Under the current library version, this is not possible without some very odd hacks. Assuming this use case seems valid, what is the work around?

**Comment by 75lb** [comment]
every time you run `commandLineArgs(definitions)` (from one module, from multiple modules, from wherever) the command line arguments (in the global `process.argv` array) are parsed using the definitions provided.

You are parsing the command line twice in the same synchronous tick. If either of those invocations are invalid you'll get errors. Maybe passing your own `argv` array to `commandLineArgs()` or using `partial: true` would help. Check the docs.

**Comment by blakewest** [comment]
A workaround I just tested out is to do something like this...
```
// Only parse command line args if you're calling this file from the command line. 
// eg. this file is scriptA, but we call scriptB from the command line, and scriptB requires scriptA. 
// This ensures we don't run scriptA's command line args parsing, which could throw an error 
// that we don't care about.
if (process.argv[1] !== __filename) {
  commandLineArgs(myOptions)
}
```
