### ISSUE TITLE
user input validation on argv values

### ISSUE THREAD

**Issue by 75lb** [75lb/command-line-args#4]
- [ ] required flag
- [ ] isValid test regexp or function

**Comment by yoiang** [comment]
Hey @75lb ! I've spun up on using **command-line-args** and it's great! I was looking around for a required flag mechanism and noticed the closed issue, is it something that you feel isn't necessary?

**Comment by 75lb** [comment]
hi @yoiang, yes it was decided to keep input validation out of the library.. it's an opinionated area and best left down-stream.. 

you can check the output of `cli.parse()` and if your required value is missing, throw an exception.

**Comment by 75lb** [comment]
glad you like the library, don't be shy to make further suggestions - all good..

**Comment by yoiang** [comment]
Gotcha, thanks :)

**Comment by XescuGC** [comment]
So the only way right now is to check the `cli.parse()`? I think the `required` flag is a really good idea.

**Comment by 75lb** [comment]
@XescuGC as i said before, `required` logic is opinionated and varies per option type.. *what* is required exactly? A value? Two values? Two values of length 3? 

The library had a `required` flag two years ago when it was born, but it was quickly removed to give the user full control over validation logic (what is and is not valid).

**Comment by XescuGC** [comment]
For me the `required` flag means that the options with this flag are required to the export to execute, maybe another name is `present` but the name i don't care 😄  it's just the idea behind it. It's not a type/format validation, it s a presence validation. Does it make sense?
