### ISSUE TITLE
Throw error if unexpected option values are present

### ISSUE THREAD

**Issue by rightaway** [75lb/command-line-args#40]
The docs say `By default, an exception is thrown if the user sets an unknown option (one without a valid definition).` But as mentioned in https://github.com/75lb/command-line-args/issues/39, if your definition is `{ name: 'file', defaultOption:true }` and command line is `$ example one.js two.js three.js`, `file` will be set to `one.js`.

But it should throw an error by default, because it means I've specified things on the command line that weren't expected, so I should either correct the command line or the definition rather than letting the program carry on because something could be wrong.

**Comment by 75lb** [comment]
yes, it will throw if an unknown option is present (e.g. `--pizza` or `-p`) but `two.js` and `three.js` are not options, they are values. 

So, you're saying the module should throw if unexpected values are present. This sounds reasonable - I will investigate in more depth tonight, thanks.

**Comment by rightaway** [comment]
That's right, I think it would be very useful to throw anytime something isn't expected. The main reason I'm looking for an arg parser is to protect me from my own silly mistakes (like entering something wrong on the command line, or something having changed during refactoring), which could lead to some subtle bugs.

Another thing I just noticed is that if I have an option like `{ name: 'arg1', type: String }`, but `--arg1` doesn't appear on the command line, there's no error thrown. I think it should also throw an error. If someone doesn't want that option, they could specify something like `optional: true` for it, and then `arg1` could appear or not appear, but by default it would be expected to be there.

But if you have a boolean `{ name: 'arg2', type: Boolean }`, then of course it couldn't be required. Because if you always want `--arg2` to be specified on the command line, then you might as well omit it since `arg2` will always be `true` in the application.

**Comment by 75lb** [comment]
Validation (including deciding whether an option value is required) is out of scope for this module - it's too opinionated, everyone does it their own way. This module parses the command line only. 

Simple validation example [here](https://github.com/75lb/command-line-args/blob/master/example/validate.js) - you'll need to do it yourself.

**Comment by 75lb** [comment]
just FYI, the next version will throw by default if either an unknown option or value are found.

**Comment by 75lb** [comment]
Implemented in [v5.0.0](https://github.com/75lb/command-line-args/releases/tag/v5.0.0).
