### ISSUE TITLE
Arguments containing newlines are parsing incorrectly

### ISSUE THREAD

**Issue by benblamey** [75lb/command-line-args#44]
Thanks for a great library!

Suppose invoke my script on bash as follows (typing my newlines directly):

```
$ npm run my-script -- --arg="foo
bar 
wibble"
```

I end up with ``arg="foo"``.

However bash seems to support this in general, suppose I do:
```
$ echo "foo
bar
wibble"
```
I see:
```
foo
bar
wibble
```

**Comment by benblamey** [comment]
I guess its actually a node bug?

**Comment by benblamey** [comment]
Node seems OK:

**Comment by 75lb** [comment]
i can't reproduce this. 

I created this script

```js
const commandLineArgs = require('command-line-args')
const optionDefinitions = [
  { name: 'one' }
]
const options = commandLineArgs(optionDefinitions)

console.error(require('util').inspect(options, { depth: 6, colors: true }))
```

and this npm script
```json
  "scripts": {
    "test": "node tmp.js"
  },
```

When i run the npm command with an arg containing a newline: 

```
$ npm test -- --one "hello
there"
```

my output is correct: 

```
{ one: 'hello\nthere' }
```
