### ISSUE TITLE
buggy handling of unknown options with partial: true, but also default option with multiple: true

### ISSUE THREAD

**Issue by cwilso03** [75lb/command-line-args#45]
Consider the following test code:

>const args = require('command-line-args');
>const optionDefs = [ { name: 'stringList', type: String, multiple: true, defaultOption: true } ];
>const options = args(optionDefs, { partial: true });
>console.log(JSON.stringify(options));
>options.stringList.forEach((item) => { console.log("got list item: '" + item + "'"); });

If you run this code with the following syntax:
`node test.js item1 item2 --unknownOpt=item3`

I would expect the following output:
>{"stringList":["item1","item2"],"_unknown":["--unknownOpt","item3"]}
>got list item: 'item1'
>got list item: 'item2'

But instead, you get this:
>{"stringList":["item1","item2","item3"],"_unknown":["--unknownOpt"]}
>got list item: 'item1'
>got list item: 'item2'
>got list item: 'item3'

As you can see, even though *'item3'* is specified with an equal sign after `--unknownOpt`, the value still gets included in the *defaultOption* *stringList*.

**Comment by 75lb** [comment]
Fixed and released in v4.0.2 - thanks for letting me know. 👍

**Comment by cwilso03** [comment]
Works perfectly now!  Thanks!
