### ISSUE TITLE
NAME_MISSING

### ISSUE THREAD

**Issue by sudoak** [75lb/command-line-args#46]
When i run the code given in README.md for  command-line-usage example, i get the following error 

NAME_MISSING: Invalid option definitions: the `name` property is required on each definition

**Comment by 75lb** [comment]
which command-line-usage example on which README?

**Comment by sudoak** [comment]
const getUsage = require('command-line-usage')

const sections = [
  {
    header: 'A typical app',
    content: 'Generates something [italic]{very} important.'
  },
  {
    header: 'Options',
    optionList: [
      {
        name: 'input',
        typeLabel: '[underline]{file}',
        description: 'The input to process.'
      },
      {
        name: 'help',
        description: 'Print this usage guide.'
      }
    ]
  }
]
const usage = getUsage(sections)
console.log(usage)

**Comment by 75lb** [comment]
that example works fine, please ensure you have the latest version of command-line-usage installed.
