### ISSUE TITLE
Simultaneously use  of defaultValue and defaultOption not possible ?

### ISSUE THREAD

**Issue by Hammster** [75lb/command-line-args#47]
Just run into this, maybe I am just missing something in the docs.

I want to have a default option, which has a default value as fallback. When I call it with the correct argument name `example --path ./whatever` it parses the value, as intended. But If I call it like a `defaultOption` via `example ./whatever` it ignores the set value and loads the `defaultValue`.

My code looks like this

```javascript
const commandLineArgs = require('command-line-args')
const optionDefinitions = [
  { name: 'path', type: String, defaultOption: true, defaultValue: './' },
]
const options = commandLineArgs(optionDefinitions)

console.log(options)
```

Cheers 😃

**Comment by 75lb** [comment]
Fixed and released in v4.0.3. Well spotted, thanks 👍
