### ISSUE TITLE
Use more secure HTTPS URLs

### ISSUE THREAD

**Issue by paulmenzel** [75lb/command-line-args#49]
On the [package page at npm](https://www.npmjs.com/package/command-line-args) the browser shows the warnings below.

> Loading mixed (insecure) display content "http://img.shields.io/npm/v/command-line-args.svg" on a secure page

GitHub currently doesn’t allow me to fork the project, so I can’t send a merge/pull request to update the `README.md`. But it’s simple enough, so it’d be great if you did it.

**Comment by 75lb** [comment]
no problem, will fix.. why does Github not allow you to fork?

**Comment by paulmenzel** [comment]
I guess it’s a temporary problem. When clicking on the fork button, nothing happens.

No idea if the console errors below are related.

> Content Security Policy: The page's settings blocked the loading of a resource at self ("script-src https://assets-cdn.github.com").
> Error: timeout loading module: github-bootstrap

**Comment by 75lb** [comment]
i see.. and why is the "mixed content" warning a problem for you? Just curious as you're the first to mention it..

**Comment by paulmenzel** [comment]
> and why is the "mixed content" warning a problem for you? Just curious as you're the first to mention it …

It’s not a problem. Just that the browser shows a yellow warning sign next to the lock symbol.

**Comment by paulmenzel** [comment]
… and it saves two requests, as shields.io redirects to HTTPS.

**Comment by 75lb** [comment]
ok.. no probs, it's a quick fix - thanks for bringing it to my attention.
