### ISSUE TITLE
Not allowing use of full name alias with `defaultOption` arg

### ISSUE THREAD

**Issue by avanderhoorn** [75lb/command-line-args#55]
I am wanting to have:
```
const optionDefinitions = [
    ...
    { name: 'script', type: String, defaultOption: true }
];
```
Currently that allows the user to use:
```
mymodule index.js

# or 

mymodule --script index.js
```
I don't want to allow the user to input the second option.

Any ideas on how I would do this or if it is/can be supported?

**Comment by 75lb** [comment]
no, this is not supported.. it's quite a strange request ("i want to define the --script option but not allow the user to use it").

what is your use case for this?

**Comment by avanderhoorn** [comment]
I'm wanting to support something like the following... Normally the user goes:
```
node index.js --foo test --bar
```

I'm creating something that essentually proxies the node command, but I want it to be simple for the user and allow them to just drop in my proxy

```
myproxy index.js --foo test --bar
```

But things get a little more hair quite quickly if i want to allow my proxy to have settings as well (where possible name collisions could occur 

```
myproxy --max 2 --foo hello index.js --foo test --bar

myproxy [myproxy args] <script> [user args]
```

To do this successfully, I need to work out the position of the `script` value so that I know where to break the `process.argv` for this to be a seamless drop in - so that I can not only pull out my args but also update `process.argv` after I have done so to make it as if my proxy (and associated args) was never there. Does that makes sense?

I was thinking that not allowing use of full name alias with `defaultOption` arg would be an easy way to do this, but that could still run into issues. What I think I really need is a helper function that could tell me the position at which the `script` arg is. Then I can go about breaking up the args. Any thoughts of a better way?

**Comment by 75lb** [comment]
thanks for the detailed description.. this sounds half way between a use case for [partial parsing](https://github.com/75lb/command-line-args#partial-parsing) and [this PR](https://github.com/75lb/command-line-args/pull/53/files).. will have a think..

**Comment by avanderhoorn** [comment]
Kinda... the issue is when there is overlap in the name of args that `myproxy` uses and the users args. I want to parse up to the point where a given arg is found (in this case `scripts`) and also to know what that point is so that I can update `process.argv` so I can make it like I was never there (so that the users code works the same as it did before).

**Comment by avanderhoorn** [comment]
Just wondering if you have had any thoughts on this one?

**Comment by 75lb** [comment]
sorry, has been a very busy week with the kids being off school.. I will be implementing a "stop parsing at the first unknown arg or a given string literal" feature next which should help you achieve what you need.

It will look something like this: 

```js
const optionDefinitions = [
  { name: 'max', type: Number }
  { name: 'foo', type: String }
]

/* stopParsingAt accepts a string literal (e.g. `--`) or a constant */
const options = commandLineArgs(optionDefinitions, {
  stopParsingAt: commandLineArgs.UNKNOWN
})
console.log(options)

/*
if process.argv equals this:
myproxy --max 2 --foo hello index.js --foo test --bar

options will equal: 

{
  max: 2,
  foo: 'hello',
  _unknown: [ 'index.js', '--foo', 'test', '--bar']
}
*/
```

You can now pass `_unknown` back to `commandLineArgs` or another parser. 

Closing this ticket as I already have a [PR open](https://github.com/75lb/command-line-args/pull/53) to implement this feature.

**Comment by avanderhoorn** [comment]
Great! In the above case, can `foo` be the default arg and hence not have the `--foo` prefix?
