### ISSUE TITLE
uglify error

### ISSUE THREAD

**Issue by zhenyulin** [75lb/command-line-args#58]
```
ERROR in client.js from UglifyJs
Unexpected token: name (ArgRegExp) [./node_modules/command-line-args/lib/option.js:3,0][client.js:14207,6]
```

**Comment by 75lb** [comment]
what is this, how exactly do I reproduce it? Is this an issue with uglify or command-line-args?

**Comment by zhenyulin** [comment]
Here's my webpack uglify plugin settings

```
new webpack.optimize.UglifyJsPlugin({
      sourceMap: true,
      minimize: true,
      comments: false,
      compress: {
        dead_code: true,
        unused: true,
        warnings: false,
        screw_ie8: true,
      },
      exclude: [/\.min\.js$/gi],
    }),
```

here's the command-line-args code

```
const commandLineOptionSchema = [{ name: 'TEST', type: String }];

const commandLineOptions = commandLineArgs(commandLineOptionSchema);

console.log('command line test: ', commandLineOptions.TEST);
```

Not sure if this is an issue for `command-line-args` or `uglify` yet, but might be easier to start looking on this end?

**Comment by 75lb** [comment]
why would you use webpack on this library? Command-line-args is not for the web, it's for node.js command-line-tools only.

**Comment by zhenyulin** [comment]
@75lb I'm trying to pass in run time environment variables with `command-ling-args` as client side code wouldn't take `process.env` after it is built.

**Comment by 75lb** [comment]
it's an issue with Uglify - the version you are using does not support ES6 code.. see [here](https://github.com/mishoo/UglifyJS2/issues/448).

**Comment by zhenyulin** [comment]
@75lb thanks for pointing this out, I've tried with https://github.com/webpack-contrib/uglifyjs-webpack-plugin, but still got the same error; the error message doesn't look like an ES6 feature here though
