### ISSUE TITLE
lib/output2.js: 'this' is not allowed before super()

### ISSUE THREAD

**Issue by renaudbardet** [75lb/command-line-args#59]
I need to transpile my application for an earlier version of node, but babel throws an error because not calling super in a subclass is not es6 compliant.

```
SyntaxError: E:/projects/Biborg/microserver/temp/node_modules/command-line-args/lib/output2.js: 'this' is not allowed before super()
  18 | class Output extends Map {
  19 |   constructor (definitions) {
> 20 |     this.definitions = definitions
     |     ^
  21 |   }
```

babel, babel-preset-es2015

**Comment by 75lb** [comment]
which version of command-line-args are you using there? That file and code does not exist in the latest code. 

To support old versions of node, you can use `command-line-args@^3`. See the Releases page for information what changed between v3 and 4. 

Closing as this is not an issue with the current module.
