### ISSUE TITLE
Problems to pass an URL with query parameters.

### ISSUE THREAD

**Issue by geekmindio** [75lb/command-line-args#62]
Hi guys!

I am having problems to receive an URL as argument. If the URL contains more than one query parameter, it is truncated in the first occurrence of '&' character.

My options definition are:

```javascript
        this.optionsDefinition = [
            { name: 'help',         alias: 'h', type: Boolean },
            { name: 'apiType',      alias: 't', type: String },
            { name: 'requestBody',  alias: 'r', type: String },
            { name: 'keyStore',     alias: 'k', type: String },
            { name: 'endPointURL',  alias: 'u', type: String },
            { name: 'password',     alias: 'p', type: String },
            { name: 'method',       alias: 'm', type: String }
        ];
```

And when I try to pass like --endPointURL=http://localhost:8080/myService?customerAreaCode=100&active=true, the URL is truncated to http://localhost:8080/myService?customerAreaCode=100.

Kind Regards,
Andre Silva

**Comment by 75lb** [comment]
`&` is a special character in terminals (bash etc).. put quotes around the URL..

`'--endPointURL=http://localhost:8080/myService?customerAreaCode=100&active=true'`

or 

`--endPointURL 'http://localhost:8080/myService?customerAreaCode=100&active=true'`
