### ISSUE TITLE
Allow "description" property in OptionDefinition

### ISSUE THREAD

**Issue by Maskime** [75lb/command-line-args#64]
Hi,

I'm using your lib with TypeScript and with the `command-line-usage`.
If I add a "description" property in the `OptionDefinition` so that the` command-line-usage` behave as expected, the typescript compiler throws an error, telling me that the property is not allowed.
I understand that you apply a separation of concern here (`command-line-args` is not supposed to handle any description this is the job of the `command-line-usage` package).
But since both are destined to work together I guess it wouldn't hurt to add a `description?:string` in the `OptionDefinition` interface.

Do you agree with that ?

**Comment by 75lb** [comment]
Hi, sorry I don't use Typescript - what exactly are you asking me to do? Ideally, tell me the line you'd like me to add.

Bear in mind this is a Javascript module and I don't intend to maintain any Typescript code. Typescript users are welcome to create and maintain their own layer on top of this module.

**Comment by Maskime** [comment]
ok so I realise, that it seems like that this issue has nothing to do with you.
Basically, someone generated a `.d.ts` file associated to your npm package (https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/command-line-args). For Typescript, this helps to strongly type any kind of object that would associated to your library. But the generated `.d.ts` does not allow the `OptionDefinition` to have a `description` field, which makes using the `command-line-usage` a bit more tricky.
So nothing on your side, I need to post this on the related
