### ISSUE TITLE
Some problem with npm start

### ISSUE THREAD

**Issue by IvanKuzyshyn** [75lb/command-line-args#65]
Command `npm start` run webpack to build some config.
I have to inject **country** parameter for example.
So, i try this
`const configSchema = [
	{ name: 'country', alias: 'c', type: String },
];
const config = commandLineArgs(configSchema);
`

But when i try run `npm start --country spain` commandLineArgs return an empty object.

What wrong in this case?
Thanks for help.

**Comment by 75lb** [comment]
you should read the `npm start` documentation. I think the command you need is something like this: 

```
npm start -- --country spain
```

**Comment by IvanKuzyshyn** [comment]
Thanks! For now it works for me!
