### ISSUE TITLE
defaultValues that are falsey are not maintained

### ISSUE THREAD

**Issue by StoneCypher** [75lb/command-line-args#7]
To reproduce create a list of options where one has a `defaultValue` of `false`, and another of any non-empty string (such as `"true"`).  Run the resulting application with no arguments.  

Note that only the string defaulted argument is present.

**Comment by 75lb** [comment]
oh really? i will try to reproduce.. can you speed things up and send me some failing code?

**Comment by 75lb** [comment]
just the failing option definition array would be enough..

**Comment by 75lb** [comment]
don't worry - i have reproduced it now..

**Comment by 75lb** [comment]
fixed and released in 1.0.2 - thanks for the report

**Comment by StoneCypher** [comment]
oh wow, i was going to submit a PR today

guess you're too fast :+1:
