### ISSUE TITLE
Add capability to set a boolean arg to false

### ISSUE THREAD

**Issue by stevenvachon** [75lb/command-line-args#71]
https://github.com/75lb/command-line-args/blob/9e13fc4ee767d8b549a7356fea77b202e3bdf2fb/test/type-boolean.js#L21-L24
https://github.com/75lb/command-line-args/blob/9e13fc4ee767d8b549a7356fea77b202e3bdf2fb/test/type-boolean.js#L47-L50

**Comment by 75lb** [comment]
Hi.. you're the first to request this, what's your use case? Do you have a boolean arg with a `defaultValue` of `true`?

**Comment by stevenvachon** [comment]
> Do you have a boolean arg with a `defaultValue` of `true`?
Yes

**Comment by 75lb** [comment]
ok.. I will add the capability to set a `Boolean` option to `false` in a future version, by a method like 

```
$ example --verbose off
```

...or

**Comment by 75lb** [comment]
On reflection, I'm having second thoughts about implementing any special behaviour to solve this as it would require fundamental changes to the way parsing and the `type` function works. Also, I couldn't find a strong standard or convention for how it should be done. You can achieve the results you need with the existing lib.

If you want this syntax: 

```
$ example --verbose off
```

Use a definition like this..

```
{ name: 'verbose', type: String }
```

..then test the output. If the user set `--verbose` then the output will be `{ verbose: '' }`. If they set `--verbose off` then the output will be `{ verbose: 'off' }`.

If you want this syntax (quite common): 

```
$ example --no-verbose
```

Create a couple of definitions like this:

```
{ name: 'verbose', type: Boolean },
{ name: 'no-verbose', type: Boolean }
```

There are other ways to do it, all perfectly reliable.
