### ISSUE TITLE
[Enhancement] Better parsing of unknown options

### ISSUE THREAD

**Issue by DethAriel** [75lb/command-line-args#75]
Right now unknown options are not parsed according to regular algorithm, e.g.

```
> const definitions = [ { name: 'thing', type: String } ]
> commandLineArgs(definitions, { partial: true, argv: [ '--thing=anything', '--two=2', '--three', '3' ] })
{ thing: 'anything', _unknown: [ '--two=2', '--three', '3' ] }
```

What I would have expected to see is maybe an additional `_parsedUnknown` property which will contain information about unknown options parsed via a regular algorithm, e.g.

```
{ 
  thing: 'anything',
  _unknown: [ '--two=2', '--three', '3' ], 
  _parsedUnknown: { 'two': '2', 'three': '3' }
}
```

I guess it would be non-trivial to determine whether `"3"` is an unknown option, or a value of option `"--three"`, but there will be no such problem when an equals sign is used

**Comment by 75lb** [comment]
The job of `_unknown` is to return unknown args *untouched*, so they can be passed further downstream into a separate parsing task. 

Internally, [this method](https://github.com/75lb/command-line-args/blob/3bfc8f61939124f608e3e833378e43014f5813e9/lib/argv.js#L31) is used to expand `--option=value` notation. I won't add a `_parsedUnknown` property, instead (eventually) I'll supply a separate module to expand `--option=value` notation but for now use this code:


```js
const argv = [ '--one=1', '--two=2' ]
const optEqualsRe = /^(--\S+?)=(.*)/
const expandedArgs = []
argv.forEach(arg => {
  const matches = arg.match(optEqualsRe)
  if (matches) {
    expandedArgs.push(matches[1], matches[2])
  } else {
    expandedArgs.push(arg)
  }
})

console.log(expandedArgs)
```

**Comment by DethAriel** [comment]
Thx for the response! Makes perfect sense for the lib, I get your point. Not that it was hard to implement something like that myself (which I did), I just initially expected the lib to handle that. Thx for all you do!

**Comment by 75lb** [comment]
In an older version, the lib *did* handle it the way you expect but this did not suit people who wanted to pass the `_unknown` values into downstream apps expecting `--option=value` notation.

**Comment by 75lb** [comment]
let me know if you find anything else as i'm working on the next release atm 👍

**Comment by 75lb** [comment]
for future reference, I created a library for working with `process.argv` args [here](https://github.com/75lb/argv-tools).
