### ISSUE TITLE
Testing my options

### ISSUE THREAD

**Issue by JKerney-HunterIndustries** [75lb/command-line-args#76]
I am working on a package using the command line args. I could find no easy way to unit test my argument configuration. It would be handy to have a test method where I can pass in an array and get the results.

This is not a large issue, but I did not know where to start a conversation.

**Comment by 75lb** [comment]
you can see an example of how I test CLI apps [here](https://github.com/lwsjs/local-web-server/blob/master/test/cli.js#L23)..First, i backup `process.argv` into `origArgv` then i manipulate `process.argv` before running the test and later restoring the original values.

**Comment by 75lb** [comment]
i'm sure there are other ways.. you could also pass test `argv` values into your main executable script (e.g. `bin/cli.js`) via environment variables..

**Comment by 75lb** [comment]
> handy to have a test method where I can pass in an array and get the results.

a test method where? On your app or this module? What would the method look like? Could you post some example pseudo-code?
