### ISSUE TITLE
camelCase option doesn't work if options are grouped

### ISSUE THREAD

**Issue by brunomorency** [75lb/command-line-args#78]
in https://github.com/75lb/command-line-args/blob/2361337f1b10b6bed19ed5e040bbca5225a0e495/index.js#L83 the `result` object passed to `optionUtil.camelCaseObject` has a different structure when option definitions are grouped so the camelCasing happens on group names instead of option names as expected.

**Comment by 75lb** [comment]
well spotted, I'll look at it now. Thanks for the report.

**Comment by 75lb** [comment]
fixed and released in v5.0.2 👍

**Comment by brunomorency** [comment]
Awesome! Thanks for this lightning fast fix
