### ISSUE TITLE
Question: How this compares to the alternatives?

### ISSUE THREAD

**Issue by mischah** [75lb/command-line-args#79]
Hej, this is something what could be mentioned in the README:

What’s the difference between `command-line-args`, `minimist` and `yargs`?

Thanks, Michael

**Comment by 75lb** [comment]
To be honest, I have never used yargs (this library pre-dates it) but I agree it's something people need to know. Is there a SO question on the topic? If not, maybe you should create one and we can contribute.

Off the top of my head.

Command-line-args: Data driven, Typescript-friendly, feature-complete (covers all known use cases). Has a flexible companion usage-generator (command-line-usage).

Minimist: Is it still maintained? Very minimal control, for simple use cases only.

Yargs: Minimist/Optimist re-visited. It is not data-driven, options are defined programmatically by chaining method invocations. This suits some but not all as sharing cli options defined this way is not as trivial as it could be. With a data-driven API, you can export common option definitions in a module and reuse them between projects. Yargs has a larger API surface with more frequent breaking-change releases (they're already up to v11).

**Comment by willxy** [comment]
Also to compare with https://github.com/tj/commander.js/ which is what I used most recently
