### ISSUE TITLE
(minor) Underlining does not work on Windows

### ISSUE THREAD

**Issue by StoneCypher** [75lb/command-line-args#8]
Bold, however, does.

Consider the following usage rule:

```javascript
{
  "title": "immaterial",
  "description": "Converts Material-JSON to Material-SASS, react/angular imperative",
  "synopsis": [
    "$ immaterial mytheme.json",
    "$ immaterial mytheme.json [[bold]{--output} [underline]{theme}] [[bold]{--verbose}] [[bold]{--silent}] [[bold]{--explicit}]",
    "$ immaterial mytheme.json [[bold]{-vse12345}] [[bold]{-o} [[underline]{theme}]]",
    "$ immaterial --help"
  ],
  "footer": "Project home: [underline]{https://github.com/StoneCypher/immaterial/}"
}
```

This renders as follows on Windows:
![immaterial help no underscore](https://cloud.githubusercontent.com/assets/77482/10166876/e8d502e0-667a-11e5-9308-7ed5536ebc1e.png)

I assume this is a result of your console formatter.

Some console formatters do give underlines correctly on Windows, such as [https://www.npmjs.com/package/cli-color](cli-color).

This probably isn't that big a deal.  Just noting it for posterity.

**Comment by 75lb** [comment]
ah, thanks for letting me know - i will fix this tonight

**Comment by 75lb** [comment]
btw, nice usage docs.. although i recommend using the `typeLabel` property (as seen in [this example](https://github.com/75lb/command-line-usage#medium-example)) to get more useful type labels than the default `string[]` etc.. 

i'm still working on these libraries so keep the suggestions coming.. i'll need maintainers, too

**Comment by StoneCypher** [comment]
Thanks.  It's just a first draft; I started this lib yesterday.

Baby Whichever Prophet You Believe In &trade; wants color

**Comment by StoneCypher** [comment]
also i prefer your lib to commander and a couple others i've tried significantly already

**Comment by 75lb** [comment]
the others didn't suit me either, hence this lib.. pleased you like it.. 

are you sure underline using cli-color works on windows? doesn't for me.. i tried it in cmd and cygwin.. i did some further research and it seems underline simply isn't supported on Windows.. if you discover otherwise, please let me know..

**Comment by StoneCypher** [comment]
The [Windows console](https://msdn.microsoft.com/en-us/library/windows/desktop/ms682088(v=vs.85).aspx#_win32_character_attributes) does indeed support underlining, using the flag `COMMON_LVB_UNDERSCORE`.

I could swear `color-cli` did, but it's been a long time since I looked.  Let me do some research and get back to you, please.
