### ISSUE TITLE
Remove support for setting non-contiguous values

### ISSUE THREAD

**Issue by rgov** [75lb/command-line-args#82]
The "partial: defaultOption" test wants it to ignore the unknown argument `--one` and then grab the following argument as a default option value. In this case,  the most obvious interpretation is that the user meant `--one file2` to be taken as an option/value pair, no one splits up default option values with flags in the middle.

This could have destructive effects if the user makes a typo. The safe behavior is to not perform partial argument parsing this way.

```js
runner.test('partial: defaultOption', function () {
  const definitions = [
    { name: 'files', type: String, defaultOption: true, multiple: true }
  ]
  const argv = [ '--files', 'file1', '--one', 'file2' ]
  const options = commandLineArgs(definitions, { argv, partial: true })
  a.deepStrictEqual(options, {
    files: [ 'file1', 'file2' ],
    _unknown: [ '--one' ]
  })
})
```

**Comment by rgov** [comment]
I can see the value in partial parsing, but it's error-prone. In the past, I've written wrapper scripts that manipulate compiler flags before invoking the real compiler with the modified argument list. Partial parsing is basically what I was doing.

However, the behavior has to be carefully considered. In this test, I might expect it to capture `file1` but then once the default option value list is ended (by the unknown `--one` argument), nothing more should be accumulated to the value list. `file2` should raise `UNKNOWN_VALUE`.

**Comment by rgov** [comment]
These two tests also check for behavior that doesn't seem necessarily desirable to me:

* **partial: string defaultOption can be set by argv once**
* **partial: string defaultOption can not be set by argv twice**

**Comment by 75lb** [comment]
> no one splits up default option values with flags in the middle.

Hmm, yeah maybe but this lib chose not to make that assumption.

> I can see the value in partial parsing, but it's error-prone.

Of course, that's why it's not the default mode (which is strict). Really, when partial-parsing the developer should be vigilant and verify the returned options (and potentially even `_unknown`) look sensible before proceeding. 

> file2 should raise UNKNOWN_VALUE.

UNKNOWN_VALUE and UNKNOWN_OPTION are not emitted during `partial` parsing, which is forgiving by design. Using the `stopAtFirstUnknown` flag ignores everything from the first unknown onward.

**Comment by 75lb** [comment]
> Ok, how about then that file2 goes into _unknown but doesn't get interpreted as a default option value anymore?

That's what the `stopAtFirstUnknown` flag is for.

**Comment by rgov** [comment]
If I have `[ '--files', 'file1', '--one', 'file2', '--two' ]`, and I define option definitions for `--files` and `--two` but not `--one`, then I'd expect:

1. `--files` gets set to `"file1"`
2. `--one` is an unknown option.
3. `file2` is an unknown value.
4. `--two` gets set to `true`

My choices are either to accept `files=["file1", "file2"]`, which isn't expected (no one splits argument arrays up like this ever), or turn on `stopAtFirstUnknown` and have `--two` not handled.

**Comment by 75lb** [comment]
i don't understand what point you are making above.. are you asking a question or are you highlighting a bug in the current behaviour? The scenario you expect above is possible with the current behaviour.

**Comment by rgov** [comment]
According to the test case cited above, it's not the current behavior. I couldn't even do it with multiple parses with `stopAtFirstUnknown` set, because, as the test case shows, `--files` would be set to `["file1", "file2"]`.

I'm trying to point out that the partial parsing mode has pitfalls. I believe the feature is unsound and it would be error-prone to use it, though it could be made more straightforward. Yes, it may be up to the developer to validate it, but how exactly do you suggest I validate it? Writing a check that says "loop over the `files` array and make sure each element appeared contiguously in the argument array"? That's time consuming, negates the benefit of using a simple declarative library, and in that case I might as well be parsing arguments manually.

**Comment by 75lb** [comment]
This config produces the output you expect:

```js
const commandLineArgs = require('command-line-args')
const argv = [ '--files', 'file1', '--one', 'file2', '--two' ]

const optionDefinitions = [
    { name: 'files', multiple: true },
    { name: 'two', type: Boolean }
]
const options = commandLineArgs(optionDefinitions, { argv, partial: true })
console.log(options)
```

Outputs: 
```
{ _unknown: [ '--one', 'file2' ], files: [ 'file1' ], two: true }
```

But that config doesn't set `files` as the `defaultOption`. If `defaultOption` _is_ set then yes, `files` will receive both `file1` and `file2` which is the expected, defined behaviour. 

> no one splits argument arrays up like this ever

I think expectations are at the heart of your issue. With this library, arg order is insignificant (the first rule mentioned in the [Notation Rules](https://github.com/75lb/command-line-args/wiki/Notation-rules)). The position `file2` appears in `argv` makes no difference. Your expectation is that arg order _should_ be significant. 

It's useful feedback and we may have a case to introduce the Strategy pattern, i.e. allow the user to set the parsing strategy used, or pass in a hand-rolled strategy. I'm also taking on board opinions on what should be the default strategy.

**Comment by rgov** [comment]
I understand that my expectations don't match the library's current behavior. But I'm wondering why this library has to be different than other argument parsers.

If I'm writing C with `getopt`, then this behavior doesn't happen. Likewise for Python with `argparse`

```
$ cp a b -r c d out
cp: -r: No such file or directory
```

As an end user, I do not know or want to care what argument parser library is used by the tool I'm invoking. I don't want it to have special notation rules that I need to be aware of. 99.99% of existing command line tools work *that way* and suddenly a handful of Node tools work *this way*. That's frustrating, and leads to wasted time troubleshooting. The conventions for command line arguments have existed for decades and people expect them to be followed.

As a developer, I want people to interact with my tool in a conventional way. I don't want them to think that my tool is buggy. I don't want the tool to do something unexpected on them. And I don't want them to get used to some funky behavior like being able to write `cp a b c -r d out` and then I have to support that non-standard behavior forever. If I ported my slow JavaScript code to C for performance, for instance, I would not be able to switch to `getopt` and maintain compatibility.

**Comment by 75lb** [comment]
I'm renaming this issue to "Remove support for setting non-contiguous values" as that's the action I believe you're looking for. If that's inaccurate or there's another action this thread needs, let me know or open a separate ticket. 👍
