### ISSUE TITLE
OptionDefinition - Type does not include description:

### ISSUE THREAD

**Issue by mashaalmemon** [75lb/command-line-args#88]
Hi There,

In docs, there is no mention of the 'description' property of an ObjectDefinition:

https://github.com/75lb/command-line-args/blob/master/doc/option-definition.md#exp_module_option-definition--OptionDefinition

But in the typical example, the 'description' property is used:

https://github.com/75lb/command-line-args/wiki/Typical-usage-example

Docs should be updated.

I noticed this when using this package with Typescript and found I was getting an error when I used 'description' as a property in an 'Option Definition'. Planning to submit a change to the DefinitelyTyped repo to fix this so that the error as well. 

Perhaps you can go ahead and fix the docs on this side?

**Comment by 75lb** [comment]
Hi, the `description` property is one of the first things mentioned in the API docs, quote:

> Describes a command-line option. Additionally, if generating a usage guide with command-line-usage you could optionally add description and typeLabel properties to each definition.

Yes, that sounds like an issue with the DefinitelyTyped types..

**Comment by 75lb** [comment]
the `description` property is required by `command-line-usage`, not `command-line-args`. It's documented here: https://github.com/75lb/command-line-usage#commandlineusageoptionlist

**Comment by mashaalmemon** [comment]
HI @75lb, you're right. Might be nice to actually have that up at the top of the doc as they are part of the definition like so?:

* [option-definition](#module_option-definition)
    * [OptionDefinition](#exp_module_option-definition--OptionDefinition) ⏏
        * [.name](#module_option-definition--OptionDefinition+name) : <code>string</code>
        * [.type](#module_option-definition--OptionDefinition+type) : <code>function</code>
        * [.alias](#module_option-definition--OptionDefinition+alias) : <code>string</code>
        * [.multiple](#module_option-definition--OptionDefinition+multiple) : <code>boolean</code>
        * [.lazyMultiple](#module_option-definition--OptionDefinition+lazyMultiple) : <code>boolean</code>
        * [.defaultOption](#module_option-definition--OptionDefinition+defaultOption) : <code>boolean</code>
        * [.defaultValue](#module_option-definition--OptionDefinition+defaultValue) : <code>\*</code>
        * [.group](#module_option-definition--OptionDefinition+group) : <code>string</code> \| <code>Array.&lt;string&gt;</code>
        * [.description](#module_option-definition--OptionDefinition+description) : <code>string</code> \| <code>Array.&lt;string&gt;</code> (Optional)
        * [.typelabel](#module_option-definition--OptionDefinition+typeLabel) : <code>string</code> \| <code>Array.&lt;string&gt;</code> (Optional)

But I leave it to you. I'll go ahead an submit a pull request to DefinitelyTyped to add these two in the type definitions.

Thanks for the quick response.

**Comment by 75lb** [comment]
Hi, like i said - the `description` property is nothing to do with `command-line-args`, it's required by `command-line-usage`. Ok, yes good idea about the PR, thanks.

**Comment by mashaalmemon** [comment]
@75lb Reading your comments more closely, I realized that OptionDefinition is defined twice, once in the '@types/command-line-args' and again in '@types/command-line-usage'. After your comment, it appears, the best approach is to use the definition from the latter.

Thanks for the clarification.
