### ISSUE TITLE
Catching "invalid option"

### ISSUE THREAD

**Issue by stefanwalther** [75lb/command-line-args#9]
Hi,

what's the best way you recommend to catch the "invalid option" problem, so if the user sets a parameter wrongly or uses a parameter which is not defined?

Beside that:
I think an option would be great to suppress this behavior, so any undefined parameter would just be ignored and no exception would be thrown.

Regards
Stefan

**Comment by 75lb** [comment]
On invalid input the library throws, it is the developer's choice what to do next - the library has no opinion..  the cases in which `.parse()` with throw are documented [here](https://github.com/75lb/command-line-args#cliparseargv--object).. it is the developer's choice what to do next.

```
try {
  var options = cli.parse();
} catch (err) {
  // it failed, your choice what to do next
  // maybe display the error and ask the user to try again
}
```

**Comment by stefanwalther** [comment]
Thx, yes, this is how I did it ... What's about implementing something like a tryParse which would allow one to proceed??

**Comment by 75lb** [comment]
Send me an example of how `.tryParse()` would be used

**Comment by 75lb** [comment]
one thing i need to add is error codes.. currently, when the library throws it sets an `err.message` (e.g. "invalid option value") but it should also set an `err.code` (e.g. "INVALID_OPTION" or similar)

**Comment by 75lb** [comment]
i've almost finished the next release, which includes improved error handling (exceptions now have [error names](https://github.com/75lb/command-line-args#new-commandlineargsdefinitions) to help differentiate).. if you have any thoughts/input, let me know soon before i put this live.. thanks
