### ISSUE TITLE
Reverse of parsing

### ISSUE THREAD

**Issue by varun-dev** [75lb/command-line-args#95]
Hi,

Is there a way to convert options back into `process.argv` format?
```
{
  src: [
    'one.js',
    'two.js'
  ],
  verbose: true,
  timeout: 1000
}
```
back to
`--verbose --timeout 1000 --src one.js two.js`

thanks

**Comment by 75lb** [comment]
no, i'm afraid not - it is not something anyone has asked for.. 

what is your use case?
