### ISSUE TITLE
Allow Special Characters

### ISSUE THREAD

**Issue by Chazza** [75lb/command-line-args#98]
Hi there,

When attempting to pass special characters (such as $, !, @ etc), it gets stripped out of the string.

For example:
`node app.js -p "qwerty$123" `

Shows:
`{ password: 'qwerty23' }`

This also happens when trying to input '@', any fix?

Config Options:
```
	{
		name: 'password',
		alias: 'p',
		type: String,
		description: 'The password for the target account',
		typeLabel: '<password>'
	},
```

Thanks.

**Comment by 75lb** [comment]
are you on Linux or Mac? If so pass this command instead (notice the single quotes):

```
node app.js -p 'qwerty$123'
```

Don't forget chars like `$` and `@` have special meaning in the *nix shell.

**Comment by Chazza** [comment]
> are you on Linux or Mac? If so pass this command instead (notice the single quotes):
> 
> ```
> node app.js -p 'qwerty$123'
> ```
> Don't forget chars like `$` and `@` have special meaning in the *nix shell.

Hey there, yep that fixed it - my bad.

I didn't know such a minor difference can do so much, I appreciate the quick reply!
